export const PLAN_SEARCH_COL = { span: 6 } as const
export const PLAN_SEARCH_DATE_COL = { span: 6 } as const

export const UI = {
  planCode: '预案编号',
  planName: '预案名称',
  planRule: '执行说明',
  planRulePlaceholder: '填写执行步骤与限制条件，不在此配置威胁判级规则。',
  disposalMode: '处置模式',
  disposalModeAuto: '自动处置',
  disposalModeManual: '人工值守',
  manualResponseSeconds: '人工响应时间',
  manualResponseUnit: '秒',
  manualResponseHint: '自动处置专用：触发后进入人工核查窗口；填 0 表示不等待，立即执行。',
  manualResponseManualHint: '人工值守模式下不启用等待窗口，所有动作均需人工核查后下发。',
  alarmLevel: '告警级别',
  planPriority: '优先级',
  temperature: '温度',
  humidity: '湿度',
  windPower: '风力',
  rainfall: '雨量',
  locatedArea: '所处区域',
  deviceGroup: '执行设备组',
  deviceFunction: '设备功能',
  counterDevice: '反制设备',
  triggerRules: '触发策略',
  triggerRuleName: '规则名称',
  triggerSortOrder: '排序',
  triggerRuleAdd: '新增规则',
  triggerRuleHint: '按温度、湿度、风力、雨量配置对应的执行设备组与设备功能，用于切换有效反制设备。',
  triggerRuleEmpty: '请至少添加一条触发策略规则',
  primaryRule: '主触发规则',
  updatedBy: '修改人',
  updatedAt: '修改时间',
  enabled: '启停',
  action: '操作',
  btnAdd: '新增预案',
  btnBatchDelete: '批量删除',
  btnDetail: '详情',
  btnEdit: '编辑',
  btnDelete: '删除',
  dialogAdd: '新增预案',
  dialogEdit: '编辑预案',
  dialogDetail: '预案详情',
  btnSave: '保存',
  btnCancel: '取消',
  saveOk: '保存成功',
  deleteOk: '已删除'
} as const
