export const PLAN_SEARCH_COL = { span: 6 } as const

export const UI = {
  planName: '预案名称',
  threatLevel: '威胁等级',
  disposalMode: '处置模式',
  disposalModeAuto: '自动处置',
  disposalModeManual: '人工值守',
  manualResponseSeconds: '人工响应时间',
  manualResponseUnit: '秒',
  manualResponseHint: '自动处置专用：触发后进入人工核查窗口；填 0 表示不等待，立即执行。',
  manualResponseManualHint: '人工值守模式下不启用等待窗口，所有动作均需人工核查后下发。',
  planPriority: '优先级',
  weatherElements: '天气要素',
  temperature: '温度',
  humidity: '湿度',
  windPower: '风力',
  rainfall: '雨量',
  locatedArea: '所处区域',
  deviceGroup: '执行设备组',
  deviceFunction: '反制动作',
  counterDevice: '反制动作',
  triggerRules: '触发策略',
  triggerRuleName: '规则名称',
  triggerSortOrder: '排序',
  triggerRuleAdd: '新增规则',
  triggerRuleHint: '按天气要素配置对应的执行设备组与反制动作，支持多条条件及「或/且」组合。',
  triggerRuleEmpty: '请至少添加一条触发策略规则',
  primaryRule: '主触发规则',
  triggerRuleCount: '触发策略条数',
  triggerRuleDesc: '策略描述',
  updatedBy: '更新人',
  updatedAt: '更新时间',
  enabled: '状态',
  action: '操作',
  btnAdd: '新增预案',
  btnBatchDelete: '批量删除',
  btnDetail: '详情',
  btnEdit: '编辑',
  btnDelete: '删除',
  dialogAdd: '新增预案',
  dialogEdit: '编辑预案',
  dialogDetail: '预案详情',
  btnSave: '保存',
  btnCancel: '取消',
  saveOk: '保存成功',
  deleteOk: '已删除'
} as const
