/** 查询栅格布局（与预案策略页一致） */
export const THREAT_SEARCH_COL = { span: 6 } as const

export const UI = {
  ruleCode: '规则编号',
  ruleName: '规则名称',
  threatLevel: '威胁等级',
  threatLevelHint:
    '由威胁评估规则输出；后续可扩展为按威胁等级关联预案，当前阶段由本列表直接关联触发预案',
  areaRegionType: '区域类型',
  areaRegionTypeHint: '与区域管理一致，枚举值在字典管理（area_region_type）中维护',
  targetType: '名单类型',
  swarmHint: '蜂群维度：同时探测机数≥3 时默认提升威胁等级，建议关联激光/高功率微波预案而非驱离。',
  swarmCount: '蜂群机数',
  targetProperty: '目标属性',
  status: '状态',
  updatedBy: '更新人',
  area: '区域',
  priority: '优先级',
  conditions: '触发条件',
  triggerPlan: '触发预案',
  triggerPlanHint: '规则命中后触发所选预案；具体设备动作由预案定义',
  enabled: '状态',
  action: '操作',
  btnAdd: '新增规则',
  btnSimulate: '模拟测试',
  btnBatchDelete: '批量删除',
  btnDetail: '详情',
  btnEdit: '编辑',
  btnDelete: '删除',
  dialogAdd: '新增规则',
  dialogEdit: '编辑规则',
  dialogSimulate: '模拟测试',
  dialogDetail: '规则详情',
  detailThreatLevel: '威胁等级',
  detailAlarmLevel: '告警等级参考',
  detailTriggerNote: '触发说明',
  detailRuleSummary: '规则摘要',
  detailLevelHint: '（可在编辑规则时调整；后续可扩展按等级关联预案）',
  detailDeviceType: '关联预案设备',
  detailDeviceFunction: '设备功能',
  btnSave: '确认编辑',
  btnCancel: '取消',
  btnAddCondition: '新增',
  conditionDelete: '删除',
  saveOk: '保存成功',
  deleteOk: '已删除',
  statusEnabled: '启用',
  statusDisabled: '停用'
} as const
